#version 430
#extension GL_GOOGLE_include_directive : require

#include "tonemap.glsl"

layout(local_size_x = BUCKET_COUNT) in;

layout(binding = 0, std430) buffer A
{
  float minLum;
  float maxLum;
  uint buf[bucketCount];
};

// not the most efficient solution, but one of the easiest
void main()
{
  const uint ind = gl_LocalInvocationIndex;
  uint res = 0;
  for (uint i = 0; i < ind; ++i)
  {
    res += buf[i];
  }
  barrier();
  buf[ind] += res;
}
